- Buscar os nomes de todos os alunos que frequentam alguma turma do professor 'JOAO PEDRO'.
SELECT ALUNO.Nome FROM ALUNO INNER JOIN ALUNO_TURMA 
ON (ALUNO.id = ALUNO_TURMA.ALUNO_id)
INNER JOIN TURMA 
ON (ALUNO_TURMA.turma_id = TURMA.id)
INNER JOIN PROFESSOR
ON (PROFESSOR.id = TURMA.PROFESSOR_id)
WHERE PROFESSOR.nome = 'JOAO PEDRO';

- Buscar os dias da semana que tenham aulas da disciplina 'MATEMATICA'.
SELECT TURMA.dia_da_semana FROM TURMA
INNER JOIN DISCIPLINA
ON DISCIPLINA.id = TURMA.DISCIPLINA_id
WHERE DISCIPLINA.nome = 'MATEMATICA';

- Buscar todos os alunos que frequentem aulas de 'MATEMATICA' e também 'FISICA'.
SELECT ALUNO.Nome FROM ALUNO INNER JOIN ALUNO_TURMA 
ON (ALUNO.id = ALUNO_TURMA.ALUNO_id)
INNER JOIN TURMA 
ON (ALUNO_TURMA.turma_id = TURMA.id)
INNER JOIN DISCIPLINA
ON DISCIPLINA.id = TURMA.DISCIPLINA_id
WHERE DISCIPLINA.nome = 'MATEMATICA' and DISCIPLINA.nome = 'FISICA';

- Buscar as disciplinas que não tenham nenhuma turma.
SELECT DISCIPLINA.nome FROM DISCIPLINA 
LEFT JOIN TURMA 
ON (DISCIPLINA.id = TURMA.DISCIPLINA_id)
WHERE TURMA.DISCIPLINA_ID IS NULL;

- Buscar os alunos que frequentem aulas de 'MATEMATICA' exceto os que frequentem 'QUIMICA'.
SELECT ALUNO.nome FROM ALUNO 
ON (ALUNO.id = ALUNO_TURMA.ALUNO_id)
INNER JOIN TURMA 
ON (ALUNO_TURMA.turma_id = TURMA.id)
INNER JOIN DISCIPLINA
ON DISCIPLINA.id = TURMA.DISCIPLINA_id
WHERE DISCIPLINA.nome = 'MATEMATICA' and DISCIPLINA.nome != 'QUIMICA'
